# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: corepack enable
    - run: yarn install --immutable
    - run: yarn build
    - run: yarn test:ci
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          artifacts/junit.xml
        check_name: Tests - ${{ matrix.node-version }}
    - name: LCOV Summary
      uses: pre-history/lcov-summary-action@v0.4.1
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
      with:
        lcov-file: artifacts/coverage/lcov.info
        comment-on-pr: true